### ISSUE TITLE
US 02.01.03

### ISSUE THREAD

**Issue by zq6UA** [CMPUT301F24breeze0/breeze0-events#43]
As an organizer, I want to create and manage my facility profile.

**Realization**

Extension of [US 02.01.01](https://github.com/orgs/CMPUT301F24breeze0/projects/1/views/1?pane=issue&itemId=82327336&issue=CMPUT301F24breeze0%7Cbreeze0-project%7C5)

Click on My Facility button, displays a facility management activity.
Display
- Text"My Facility"
- FacilityList(FacilityList will be store in both organizer DB and Overall DB)

Button
- My Events
- New

Click on any facility on the FacilityList, display a fragments.
Display
- Text"Edit/Delete Facility"
- Facility Name 
- Facility ID

Button
- Cancel
- Edit 
- Delete

Click on Edit button leads to another fragment
Display
- Text "Edit Facility"
- Facility Name enter space
- Facility ID enter space

Button
- Confirm
- Cancel

Click on confirm to update changes.

Click on New button on facility management activity, display a fragment.
Display
- Text "Create New Facility"
- Facility Name enter space
- Facility ID enter space

Button
- Confirm
- Cancel
Click on Confirm button to create facility.

**Comment by yuhui15** [comment]
have completed the activity to view facility

**Comment by yuhui15** [comment]
have completed the activity to add facility

**Comment by yuhui15** [comment]
Implement OrganizerFacilityActivity to create and manage the facility profile

**Comment by yuhui15** [comment]
Implementation
1. use the function  loadFacilities() to get the list of the entire facilities from the collection "FacilityDB" 
2. use the function findSmallestAvailableId() to get the smallest id that can be used to create the new facility.
3. If we want to edit or delete the facility, we need to long click the item from the Listview, then the TaskFragment will pop out and we can edit the facility through the Editview and then we use updateFacility from OverallStorage to update the data with facilityId in the collection "FacilityDB"

**Comment by yuhui15** [comment]
UI Test
1.use the function testAddFacilitySuccessfully to test whether we can add the facility successfully through User Interface.
2.use Espresso to fill the blank of facilityId and facilityname and then to click the button "Add" to add the facility
3.use the function getFacility from OverallStorageController with the parameter facilityId to retrieve the data from the collection "FacilityDB" to check whether the facility has been successfully added.
